In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [4]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.drop(axis=1,columns=['RowNumber','Surname'],inplace=True)

In [6]:
df.drop(axis=1,columns=['CustomerId'],inplace=True)

In [7]:
X=df.iloc[:,:-1].values

In [8]:
y=df.iloc[:,-1].values

In [10]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,2])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=7)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [32]:
from sklearn.ensemble import RandomForestClassifier
for i in range(1,100):
  classifier=RandomForestClassifier(n_estimators=i,criterion='entropy',random_state=0)
  classifier.fit(X_train,y_train)
  y_pred=classifier.predict(X_test)
  print(i,accuracy_score(y_test,y_pred))

1 0.7772
2 0.8272
3 0.8228
4 0.8444
5 0.8444
6 0.8492
7 0.8496
8 0.8532
9 0.8508
10 0.8508
11 0.8556
12 0.8552
13 0.8548
14 0.8568
15 0.8548
16 0.8552
17 0.8568
18 0.8572
19 0.8584
20 0.8584
21 0.8604
22 0.8576
23 0.8604
24 0.8568
25 0.86
26 0.8584
27 0.8612
28 0.8624
29 0.8628
30 0.8608
31 0.862
32 0.8612
33 0.8636
34 0.86
35 0.8616
36 0.862
37 0.862
38 0.8652
39 0.8648
40 0.8676
41 0.8656
42 0.8656
43 0.8644
44 0.862
45 0.862
46 0.8612
47 0.8628
48 0.8616
49 0.862
50 0.8616
51 0.8624
52 0.864
53 0.864
54 0.8636
55 0.8632
56 0.8616
57 0.8628
58 0.8612
59 0.8616
60 0.8608
61 0.8604
62 0.8612
63 0.8608
64 0.8608
65 0.8608
66 0.8616
67 0.8616
68 0.8616
69 0.8604
70 0.8612
71 0.8616
72 0.862
73 0.8616
74 0.8616
75 0.8612
76 0.8616
77 0.8616
78 0.8608
79 0.8604
80 0.8604
81 0.8604
82 0.862
83 0.8616
84 0.8612
85 0.8612
86 0.8616
87 0.8612
88 0.8612
89 0.862
90 0.862
91 0.862
92 0.8628
93 0.8616
94 0.8616
95 0.8612
96 0.8604
97 0.8612
98 0.8612
99 0.862


In [34]:
classifier=RandomForestClassifier(n_estimators=40,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [35]:
y_pred=classifier.predict(X_test)

In [36]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1924   66]
 [ 265  245]]


0.8676

In [29]:
from sklearn.linear_model import LogisticRegression
lc=LogisticRegression(penalty="l2",fit_intercept=False,random_state=7)
lc.fit(X_train,y_train)

LogisticRegression(fit_intercept=False, random_state=7)

In [30]:
y_predictt=lc.predict(X_test)

In [31]:
con=confusion_matrix(y_test,y_predictt)
print(con)
accuracy_score(y_test,y_predictt)

[[1181  809]
 [ 100  410]]


0.6364